using Microsoft.JSInterop;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mes_opc_ui.Services
{
    public class LocalizationService
    {
        private readonly IJSRuntime _js;
        private string _currentLang = "fr";

        public event Action? OnLanguageChanged;

        public static readonly List<LanguageOption> AvailableLanguages = new()
        {
            new("fr", "Français", "🇫🇷", false),
            new("en", "English",  "🇬🇧", false),
            new("ar", "العربية",  "🇸🇦", true),
        };

        public string CurrentLang => _currentLang;
        public bool IsRtl => _currentLang == "ar";

        public LocalizationService(IJSRuntime js) => _js = js;

        public async Task InitAsync()
        {
            var saved = await _js.InvokeAsync<string?>("mesLocalization.getLanguage");
            if (string.IsNullOrEmpty(saved))
            {
                var browser = await _js.InvokeAsync<string>("mesLocalization.getBrowserLanguage");
                saved = AvailableLanguages.Any(l => l.Code == browser) ? browser : "fr";
            }
            await ApplyLanguageAsync(saved, notify: true);
        }

        public async Task SetLanguageAsync(string lang)
        {
            if (lang == _currentLang) return;
            await ApplyLanguageAsync(lang, notify: true);
        }

        private async Task ApplyLanguageAsync(string lang, bool notify)
        {
            _currentLang = lang;
            var isRtl = lang == "ar";
            await _js.InvokeVoidAsync("mesLocalization.setLanguage", lang);
            await _js.InvokeVoidAsync("mesLocalization.setDirection", isRtl);
            if (notify) OnLanguageChanged?.Invoke();
        }

        public string T(string key)
        {
            if (_translations.TryGetValue(_currentLang, out var dict) &&
                dict.TryGetValue(key, out var val))
                return val;
            return key;
        }

        private readonly Dictionary<string, Dictionary<string, string>> _translations = new()
        {
            ["fr"] = new()
            {
                ["common.save"]             = "Enregistrer",
                ["common.cancel"]           = "Annuler",
                ["common.refresh"]          = "Rafraîchir",
                ["common.actions"]          = "ACTIONS",
                ["common.new"]              = "+ Nouveau",
                ["common.status"]           = "STATUT",
                ["common.loading"]          = "Chargement...",
                ["common.no_data"]          = "Aucune donnée.",
                ["common.active"]           = "ON",
                ["common.inactive"]         = "OFF",
                ["common.back"]             = "← Retour",
                ["common.none"]             = "Aucun",
                ["common.since"]            = "Depuis",
                ["common.until"]            = "Jusqu'à",
                ["common.limit"]            = "Limite",
                ["common.select"]           = "-- Sélectionner --",
                ["sidebar.operator_view"]   = "VUE OPÉRATEUR",
                ["sidebar.dashboard_rt"]    = "Dashboard Realtime",
                ["sidebar.configuration"]   = "CONFIGURATION",
                ["sidebar.analytics"]       = "ANALYTICS",
                ["sidebar.kpis"]            = "Configuration rapport",
                ["common.delete"]            = "Supprimer",
                ["common.search"]            = "Rechercher...",
                ["common.add"]               = "Ajouter",
                ["analytics.definitions"]    = "Définitions",
                ["analytics.new_def"]        = "+ Nouvelle",
                ["analytics.search_def"]     = "Rechercher une définition...",
                ["analytics.all_machines"]   = "Toutes machines",
                ["analytics.select_or_new"]  = "Sélectionnez une définition ou créez-en une nouvelle",
                ["analytics.new_def_title"]  = "Nouvelle Définition",
                ["analytics.info"]           = "Informations",
                ["analytics.def_name"]       = "Nom de la définition",
                ["analytics.machine_opt"]    = "Machine (optionnel)",
                ["analytics.all_machines_opt"]= "-- Toutes les machines --",
                ["analytics.modify_def"]     = "Modifier la définition",
                ["analytics.search_item"]    = "Rechercher un item...",
                ["analytics.add_item"]       = "+ Ajouter un item",
                ["analytics.no_items"]       = "Aucun item configuré pour cette définition.",
                ["analytics.no_items_search"]= "Aucun item ne correspond à la recherche.",
                ["analytics.edit_item"]      = "Modifier l'item",
                ["analytics.add_item_title"] = "Ajouter un item",
                ["analytics.field_name"]     = "Nom du champ",
                ["analytics.source"]         = "Source",
                ["analytics.aggregation"]    = "Agrégation",
                ["analytics.scope"]          = "Portée",
                ["analytics.unit"]           = "Unité",
                ["analytics.tag_node_id"]    = "Tag Node Id",
                ["analytics.lookback"]       = "Lookback (min)",
                ["sidebar.settings"]        = "Langues",
                ["common.total"]            = "TOTAL",
                ["common.active"]           = "Actif",
                ["common.inactive"]         = "Inactif",
                ["col.id"]                  = "ID",
                ["col.machine"]             = "MACHINE",
                ["col.url"]                 = "URL ENDPOINT",
                ["col.type"]                = "TYPE",
                ["col.name"]                = "NOM",
                ["col.line"]                = "LIGNE",
                ["col.description"]         = "DESCRIPTION",
                ["col.source"]              = "SOURCE",
                ["col.time"]                = "HEURE",
                ["page.endpoints.title"]    = "OPC Endpoints",
                ["page.endpoints.subtitle"] = "Gestion des endpoints OPC-UA",
                ["page.machines.title"]     = "Machines",
                ["page.machines.subtitle"]  = "Configuration du parc machines",
                ["page.machines.active_only"]= "Afficher seulement actifs",
                ["page.rules.title"]        = "Cycle Rules",
                ["page.rules.subtitle"]     = "Configuration des règles de détection de cycles",
                ["page.rules.general"]      = "Général",
                ["page.rules.start"]        = "Condition de Début (Start)",
                ["page.activity.title"]     = "Activité Récente",
                ["page.activity.subtitle"]  = "Traçabilité",
                ["page.activity.breadcrumb"]= "Acceuil",
                ["page.activity.empty"]     = "Aucune activité pour ce filtre.",
                ["page.ui.title"]           = "UI Management",
                ["page.ui.subtitle"]        = "Gestion des dashboards (défaut, création, suppression)",
                ["page.ui.search"]          = "Rechercher un dashboard...",
                ["page.analytics.title"]    = "Analytics",
                ["page.analytics.subtitle"] = "KPI et Résumés",
                ["page.reports.title"]      = "Rapports Analytics",
                ["page.reports.subtitle"]   = "Résultats de production",
                ["page.dashboard.title"]     = "Vue d'ensemble",
                ["page.dashboard.subtitle"]  = "État général du système — mis à jour en temps réel.",
                ["page.dashboard.kpi.endpoints"] = "Endpoints actifs",
                ["page.dashboard.kpi.machines"]  = "Machines configurées",
                ["page.dashboard.kpi.rules"]     = "Cycle rules actives",
                ["page.activity.view_all"]   = "Voir tout",
                ["page.activity.history"]    = "Historique complet des actions et événements système.",
                ["page.activity.filter.all"]   = "Tout",
                ["page.activity.filter.config"]= "Configuration",
                ["page.activity.filter.opc"]   = "OPC Endpoints",
                ["page.activity.filter.machines"]= "Machines",
                ["page.activity.filter.analytics"]= "Analytics",
                ["page.activity.filter.errors"]   = "Erreurs",
                ["common.loading_ui"]       = "Chargement de la configuration...",
                ["common.error_fetch"]      = "Erreur de connexion (Failed to fetch)",
                ["common.no_dashboard"]     = "⚠ Aucun dashboard trouvé",
                ["common.no_dashboard_desc"]= "Veuillez créer un dashboard UI dans l'administration.",
                ["common.disconnected"]     = "Déconnecté",
                ["common.connected"]        = "Connecté",
                ["common.connection_error"] = "Erreur",
                ["common.reconnect"]        = "Reconnecter",
                ["common.select_machine"]   = "-- Sélectionner une machine --",
                ["col.machine_code"]        = "CODE MACHINE",
                ["col.machine_name"]        = "NOM MACHINE",
                ["col.active"]              = "ACTIF",
                ["col.rule_name"]           = "NOM DE LA RÈGLE",
                ["col.rule_type"]           = "TYPE",
                ["col.target_node"]         = "NOEUD CIBLE",
                ["col.def_name"]            = "NOM DÉFINITION",
                ["col.kpi_count"]           = "NB KPIS",
                ["col.item_count"]          = "NB ITEMS",
                ["col.event"]               = "ÉVÉNEMENT",
                ["col.event_type.add"]       = "Ajout",
                ["col.event_type.modify"]    = "Modif.",
                ["col.event_type.delete"]    = "Suppr.",
                ["col.event_type.error"]     = "Erreur",
                ["col.event_type.success"]   = "Succès",
                ["page.activity.count"]      = "{0} événements affichés sur {1}"
            },
            ["en"] = new()
            {
                ["common.save"]             = "Save",
                ["common.cancel"]           = "Cancel",
                ["common.refresh"]          = "Refresh",
                ["common.actions"]          = "ACTIONS",
                ["common.new"]              = "+ New",
                ["common.status"]           = "STATUS",
                ["common.loading"]          = "Loading...",
                ["common.no_data"]          = "No data available.",
                ["common.active"]           = "ON",
                ["common.inactive"]         = "OFF",
                ["common.back"]             = "← Back",
                ["common.none"]             = "None",
                ["common.since"]            = "Since",
                ["common.until"]            = "Until",
                ["common.limit"]            = "Limit",
                ["common.select"]           = "-- Select --",
                ["sidebar.operator_view"]   = "OPERATOR VIEW",
                ["sidebar.dashboard_rt"]    = "Realtime Dashboard",
                ["sidebar.configuration"]   = "CONFIGURATION",
                ["sidebar.analytics"]       = "ANALYTICS",
                ["sidebar.kpis"]            = "Report Configuration",
                ["common.delete"]            = "Delete",
                ["common.search"]            = "Search...",
                ["common.add"]               = "Add",
                ["analytics.definitions"]    = "Definitions",
                ["analytics.new_def"]        = "+ New",
                ["analytics.search_def"]     = "Search a definition...",
                ["analytics.all_machines"]   = "All machines",
                ["analytics.select_or_new"]  = "Select a definition or create a new one",
                ["analytics.new_def_title"]  = "New Definition",
                ["analytics.info"]           = "Information",
                ["analytics.def_name"]       = "Definition name",
                ["analytics.machine_opt"]    = "Machine (optional)",
                ["analytics.all_machines_opt"]= "-- All machines --",
                ["analytics.modify_def"]     = "Edit definition",
                ["analytics.search_item"]    = "Search an item...",
                ["analytics.add_item"]       = "+ Add item",
                ["analytics.no_items"]       = "No items configured for this definition.",
                ["analytics.no_items_search"]= "No item matches the search.",
                ["analytics.edit_item"]      = "Edit item",
                ["analytics.add_item_title"] = "Add item",
                ["analytics.field_name"]     = "Field name",
                ["analytics.source"]         = "Source",
                ["analytics.aggregation"]    = "Aggregation",
                ["analytics.scope"]          = "Scope",
                ["analytics.unit"]           = "Unit",
                ["analytics.tag_node_id"]    = "Tag Node Id",
                ["analytics.lookback"]       = "Lookback (min)",
                ["sidebar.settings"]        = "Languages",
                ["common.total"]            = "TOTAL",
                ["col.id"]                  = "ID",
                ["col.machine"]             = "MACHINE",
                ["col.url"]                 = "ENDPOINT URL",
                ["col.type"]                = "TYPE",
                ["col.name"]                = "NAME",
                ["col.line"]                = "LINE",
                ["col.description"]         = "DESCRIPTION",
                ["col.source"]              = "SOURCE",
                ["col.time"]                = "TIME",
                ["page.endpoints.title"]    = "OPC Endpoints",
                ["page.endpoints.subtitle"] = "Manage OPC-UA endpoints",
                ["page.machines.title"]     = "Machines",
                ["page.machines.subtitle"]  = "Machine park configuration",
                ["page.machines.active_only"]= "Show active only",
                ["page.rules.title"]        = "Cycle Rules",
                ["page.rules.subtitle"]     = "Cycle detection rules configuration",
                ["page.rules.general"]      = "General",
                ["page.rules.start"]        = "Start Condition",
                ["page.activity.title"]     = "Recent Activity",
                ["page.activity.subtitle"]  = "Traceability",
                ["page.activity.breadcrumb"]= "Home",
                ["page.activity.empty"]     = "No activity for this filter.",
                ["page.ui.title"]           = "UI Management",
                ["page.ui.subtitle"]        = "Dashboard management (default, create, delete)",
                ["page.ui.search"]          = "Search a dashboard...",
                ["page.analytics.title"]    = "Analytics",
                ["page.analytics.subtitle"] = "KPI and Summaries",
                ["page.reports.title"]      = "Analytics Reports",
                ["page.reports.subtitle"]   = "Production results",
                ["page.dashboard.title"]     = "Overview",
                ["page.dashboard.subtitle"]  = "System status — updated in real time.",
                ["page.dashboard.kpi.endpoints"] = "Active endpoints",
                ["page.dashboard.kpi.machines"]  = "Configured machines",
                ["page.dashboard.kpi.rules"]     = "Active cycle rules",
                ["page.activity.view_all"]   = "View all",
                ["page.activity.history"]    = "Complete history of system actions and events.",
                ["page.activity.filter.all"]   = "All",
                ["page.activity.filter.config"]= "Configuration",
                ["page.activity.filter.opc"]   = "OPC Endpoints",
                ["page.activity.filter.machines"]= "Machines",
                ["page.activity.filter.analytics"]= "Analytics",
                ["page.activity.filter.errors"]   = "Errors",
                ["common.loading_ui"]       = "Loading configuration...",
                ["common.error_fetch"]      = "Connection error (Failed to fetch)",
                ["common.no_dashboard"]     = "⚠ No dashboard found",
                ["common.no_dashboard_desc"]= "Please create a UI dashboard in the administration area.",
                ["common.disconnected"]     = "Disconnected",
                ["common.connected"]        = "Connected",
                ["common.connection_error"] = "Error",
                ["common.reconnect"]        = "Reconnect",
                ["common.select_machine"]   = "-- Select a machine --",
                ["col.machine_code"]        = "MACHINE CODE",
                ["col.machine_name"]        = "MACHINE NAME",
                ["col.active"]              = "ACTIVE",
                ["col.rule_name"]           = "RULE NAME",
                ["col.rule_type"]           = "TYPE",
                ["col.target_node"]         = "TARGET NODE",
                ["col.def_name"]            = "DEFINITION NAME",
                ["col.kpi_count"]           = "KPI COUNT",
                ["col.item_count"]          = "ITEM COUNT",
                ["col.event"]               = "EVENT",
                ["col.event_type.add"]       = "Add",
                ["col.event_type.modify"]    = "Modif.",
                ["col.event_type.delete"]    = "Delete",
                ["col.event_type.error"]     = "Error",
                ["col.event_type.success"]   = "Success",
                ["page.activity.count"]      = "{0} events shown out of {1}"
            },
            ["ar"] = new()
            {
                ["common.save"]             = "حفظ",
                ["common.cancel"]           = "إلغاء",
                ["common.refresh"]          = "تحديث",
                ["common.actions"]          = "إجراءات",
                ["common.new"]              = "+ جديد",
                ["common.status"]           = "الحالة",
                ["common.loading"]          = "جاري التحميل...",
                ["common.no_data"]          = "لا توجد بيانات.",
                ["common.active"]           = "مفعل",
                ["common.inactive"]         = "معطل",
                ["common.back"]             = "← رجوع",
                ["common.none"]             = "لا شيء",
                ["common.since"]            = "منذ",
                ["common.until"]            = "حتى",
                ["common.limit"]            = "الحد",
                ["common.select"]           = "-- اختيار --",
                ["sidebar.operator_view"]   = "عرض المشغل",
                ["sidebar.dashboard_rt"]    = "لوحة التحكم المباشرة",
                ["sidebar.configuration"]   = "الإعدادات",
                ["sidebar.analytics"]       = "تحليلات",
                ["sidebar.kpis"]            = "إعداد التقرير",
                ["common.delete"]            = "حذف",
                ["common.search"]            = "بحث...",
                ["common.add"]               = "إضافة",
                ["analytics.definitions"]    = "التعريفات",
                ["analytics.new_def"]        = "+ جديد",
                ["analytics.search_def"]     = "البحث عن تعريف...",
                ["analytics.all_machines"]   = "جميع الآلات",
                ["analytics.select_or_new"]  = "اختر تعريفاً أو أنشئ جديداً",
                ["analytics.new_def_title"]  = "تعريف جديد",
                ["analytics.info"]           = "معلومات",
                ["analytics.def_name"]       = "اسم التعريف",
                ["analytics.machine_opt"]    = "الآلة (اختياري)",
                ["analytics.all_machines_opt"]= "-- جميع الآلات --",
                ["analytics.modify_def"]     = "تعديل التعريف",
                ["analytics.search_item"]    = "البحث عن عنصر...",
                ["analytics.add_item"]       = "+ إضافة عنصر",
                ["analytics.no_items"]       = "لا توجد عناصر لهذا التعريف.",
                ["analytics.no_items_search"]= "لا يوجد عنصر يطابق البحث.",
                ["analytics.edit_item"]      = "تعديل العنصر",
                ["analytics.add_item_title"] = "إضافة عنصر",
                ["analytics.field_name"]     = "اسم الحقل",
                ["analytics.source"]         = "المصدر",
                ["analytics.aggregation"]    = "التجميع",
                ["analytics.scope"]          = "النطاق",
                ["analytics.unit"]           = "الوحدة",
                ["analytics.tag_node_id"]    = "معرف العقدة",
                ["analytics.lookback"]       = "الإطار الزمني (دقيقة)",
                ["sidebar.settings"]        = "اللغات",
                ["common.total"]            = "الإجمالي",
                ["common.active"]           = "نشط",
                ["common.inactive"]         = "غير نشط",
                ["col.id"]                  = "المعرف",
                ["col.machine"]             = "الآلة",
                ["col.url"]                 = "رابط نقطة النهاية",
                ["col.type"]                = "النوع",
                ["col.name"]                = "الاسم",
                ["col.line"]                = "الخط",
                ["col.description"]         = "الوصف",
                ["col.source"]              = "المصدر",
                ["col.time"]                = "الوقت",
                ["page.endpoints.title"]    = "نقاط اتصال OPC",
                ["page.endpoints.subtitle"] = "إدارة نقاط اتصال OPC-UA",
                ["page.machines.title"]     = "الآلات",
                ["page.machines.subtitle"]  = "إعدادات المصنع",
                ["page.machines.active_only"]= "عرض النشط فقط",
                ["page.rules.title"]        = "قواعد الدورات",
                ["page.rules.subtitle"]     = "تكوين قواعد كشف دورات الإنتاج",
                ["page.rules.general"]      = "عام",
                ["page.rules.start"]        = "شرط البداية",
                ["page.activity.title"]     = "آخر الأنشطة",
                ["page.activity.subtitle"]  = "سجل التتبع",
                ["page.activity.breadcrumb"]= "الرئيسية",
                ["page.activity.empty"]     = "لايوجد أنشطة لهذا الفلتر",
                ["page.ui.title"]           = "لوحات التحكم",
                ["page.ui.subtitle"]        = "إدارة لوحات التحكم (الافتراضي، الإنشاء، الحذف)",
                ["page.ui.search"]          = "البحث عن لوحة تحكم...",
                ["page.analytics.title"]    = "تحليلات",
                ["page.analytics.subtitle"] = "مؤشرات و ملخصات",
                ["page.reports.title"]      = "تقارير الإنتاج",
                ["page.reports.subtitle"]   = "نتائج الدورات المكتملة",
                ["page.dashboard.title"]     = "نظرة عامة",
                ["page.dashboard.subtitle"]  = "الحالة العامة للنظام — تحديث في الوقت الفعلي.",
                ["page.dashboard.kpi.endpoints"] = "نقاط الاتصال النشطة",
                ["page.dashboard.kpi.machines"]  = "الآلات المكوّنة",
                ["page.dashboard.kpi.rules"]     = "قواعد الدورات النشطة",
                ["page.activity.view_all"]   = "عرض الكل",
                ["page.activity.history"]    = "السجل الكامل للإجراءات وأحداث النظام.",
                ["page.activity.filter.all"]   = "الكل",
                ["page.activity.filter.config"]= "الإعداد",
                ["page.activity.filter.opc"]   = "نقاط OPC",
                ["page.activity.filter.machines"]= "الآلات",
                ["page.activity.filter.analytics"]= "التحليلات",
                ["page.activity.filter.errors"]   = "الأخطاء",
                ["common.loading_ui"]       = "جاري تحميل الإعدادات...",
                ["common.error_fetch"]      = "خطأ في الاتصال بالسيرفر",
                ["common.no_dashboard"]     = "⚠ لم يتم العثور على لوحة تحكم",
                ["common.no_dashboard_desc"]= "يرجى إنشاء لوحة تحكم في منطقة الإدارة.",
                ["common.disconnected"]     = "غير متصل",
                ["common.connected"]        = "متصل",
                ["common.connection_error"] = "خطأ في الاتصال",
                ["common.reconnect"]        = "إعادة الاتصال",
                ["common.select_machine"]   = "-- اختر آلة --",
                ["col.machine_code"]        = "رمز الآلة",
                ["col.machine_name"]        = "اسم الآلة",
                ["col.active"]              = "نشط",
                ["col.rule_name"]           = "اسم القاعدة",
                ["col.rule_type"]           = "النوع",
                ["col.target_node"]         = "الرابط المستهدف",
                ["col.def_name"]            = "اسم التعريف",
                ["col.kpi_count"]           = "عدد المؤشرات",
                ["col.item_count"]          = "عدد العناصر",
                ["col.event"]               = "الحدث",
                ["col.event_type.add"]       = "إضافة",
                ["col.event_type.modify"]    = "تعديل",
                ["col.event_type.delete"]    = "حذف",
                ["col.event_type.error"]     = "خطأ",
                ["col.event_type.success"]   = "نجاح",
                ["page.activity.count"]      = "يُعرض {0} حدث من أصل {1}"
            }
        };
    }

    public record LanguageOption(string Code, string NativeName, string Emoji, bool IsRtl);
}
